# Generated by Django 2.1.5 on 2019-01-14 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cedula', models.CharField(max_length=255)),
                ('tarjetacredito', models.CharField(max_length=255)),
                ('limitecredito', models.FloatField()),
                ('tipopersona', models.CharField(max_length=12)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cedula', models.CharField(max_length=255)),
                ('tandalabor', models.CharField(max_length=255)),
                ('porc_com', models.FloatField()),
                ('fechaingreso', models.DateField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiene_rayaduras', models.BooleanField(default=False)),
                ('tiene_goma_repuesta', models.BooleanField(default=False)),
                ('tiene_gato', models.BooleanField(default=False)),
                ('tiene_roturas_cristal', models.BooleanField(default=False)),
                ('estado_gomas', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('cantidad_commbustible', models.CharField(max_length=10)),
                ('estado', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rent_car.Cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rent_car.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rent_car.Marca')),
            ],
        ),
        migrations.CreateModel(
            name='RentaxDevolucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_renta', models.DateTimeField(auto_now=True)),
                ('fecha_devolucion', models.DateTimeField()),
                ('montoxdia', models.FloatField()),
                ('cantidad_dias', models.IntegerField()),
                ('comentario', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rent_car.Cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rent_car.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='TipoCombustible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
                ('chasis', models.CharField(max_length=255)),
                ('motor', models.CharField(max_length=255)),
                ('placa', models.CharField(max_length=255)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rent_car.Marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rent_car.Modelo')),
                ('tipocombustible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rent_car.TipoCombustible')),
                ('tipovechiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rent_car.TipoVehiculo')),
            ],
        ),
        migrations.AddField(
            model_name='rentaxdevolucion',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rent_car.Vehiculo'),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rent_car.Vehiculo'),
        ),
    ]
