# Generated by Django 2.1.5 on 2019-01-18 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_car', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='tipovechiculo',
            new_name='tipovehiculo',
        ),
    ]
