# Generated by Django 2.1.5 on 2019-01-18 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_car', '0002_auto_20190118_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspeccion',
            old_name='cantidad_commbustible',
            new_name='cantidad_combustible',
        ),
    ]
